(() => {
  const TAU = Math.PI * 2;
  const rand = (a,b) => a + Math.random() * (b-a);
  const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
  function fit(canvas) { const r=canvas.getBoundingClientRect(), d=Math.min(devicePixelRatio||1,2); canvas.width=r.width*d; canvas.height=r.height*d; const c=canvas.getContext('2d'); c.setTransform(d,0,0,d,0,0); return [r.width,r.height,c]; }

  function hero() {
    const canvas=document.getElementById('heroCanvas'); let pts=[]; let t=0;
    function frame(){ const [w,h,c]=fit(canvas); if(!pts.length){for(let i=0;i<38;i++)pts.push({x:w/2+rand(-10,10),y:h/2+rand(-10,10),a:rand(0,TAU),life:rand(0,1)});} c.fillStyle='rgba(7,16,29,.18)';c.fillRect(0,0,w,h); c.globalCompositeOperation='lighter';
      pts.forEach(p=>{const goal={x:w/2+Math.cos(p.a)*w*.34,y:h/2+Math.sin(p.a)*h*.36};p.a+=rand(-.07,.07)+(goal.x-p.x)*.0002;p.x+=Math.cos(p.a)*.8;p.y+=Math.sin(p.a)*.8;p.x=clamp(p.x,0,w);p.y=clamp(p.y,0,h);c.strokeStyle='rgba(243,190,56,.25)';c.lineWidth=rand(1,3);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x-Math.cos(p.a)*20,p.y-Math.sin(p.a)*20);c.stroke();c.fillStyle='rgba(243,190,56,.7)';c.beginPath();c.arc(p.x,p.y,1.5,0,TAU);c.fill();}); c.globalCompositeOperation='source-over'; t++; requestAnimationFrame(frame)} frame();
  }

  function growth() {
    const canvas=document.getElementById('growthCanvas'), start=document.getElementById('growthStart'), reset=document.getElementById('growthReset'), count=document.getElementById('foodCount'), out=document.getElementById('foodCountValue'), phase=document.getElementById('growthPhase'), explain=document.getElementById('simExplain');
    let mode='food', running=false, tick=0, raf, data={};
    const copy={food:'The mould grows outward, senses food, and reinforces connected tubes.',tsp:'Several candidate routes are explored before the strongest connected tour remains.',tokyo:'Station-sized food sources guide a branching network toward an efficient rail-like shape.',mumbai:'The same growth logic is shown as a transport network between Mumbai stations.'};
    function pointsFor(w,h,kind){if(kind==='food')return Array.from({length:+count.value},(_,i)=>{const a=-Math.PI*.82+i/(+count.value-1||1)*Math.PI*1.64;return{x:w/2+Math.cos(a)*w*.36,y:h/2+Math.sin(a)*h*.36}});if(kind==='tsp')return Array.from({length:9},(_,i)=>{const a=-Math.PI/2+i/9*TAU;return{x:w/2+Math.cos(a)*w*.35,y:h/2+Math.sin(a)*h*.35}});return kind==='tokyo'?[['Shinjuku',.18,.2],['Ueno',.48,.17],['Asakusa',.78,.25],['Shibuya',.21,.54],['Tokyo',.52,.5],['Chiba',.84,.55],['Yokohama',.28,.82],['Haneda',.67,.82]].map(v=>({label:v[0],x:v[1]*w,y:v[2]*h})):['Churchgate','Dadar','Kurla','Ghatkopar','Thane','Vashi','Panvel','CST'].map((label,i)=>({label,x:[.12,.28,.4,.55,.72,.83,.77,.24][i]*w,y:[.82,.62,.48,.33,.23,.58,.8,.73][i]*h}));}
    function routeFrom(nodes){const route=[nodes[0]], remaining=nodes.slice(1);while(remaining.length){const last=route[route.length-1];let best=0,bd=Infinity;remaining.forEach((p,i)=>{const d=Math.hypot(p.x-last.x,p.y-last.y);if(d<bd){bd=d;best=i}});route.push(remaining.splice(best,1)[0])}return route}
    function makeRoute(a,b,bend=.12){const pts=[a];for(let i=1;i<5;i++){const q=i/5;pts.push({x:a.x+(b.x-a.x)*q+rand(-1,1)*canvas.clientWidth*bend,y:a.y+(b.y-a.y)*q+rand(-1,1)*canvas.clientHeight*bend})}pts.push(b);return pts}
    function init(){const [w,h]=fit(canvas);tick=0;running=false;cancelAnimationFrame(raf);data.nodes=pointsFor(w,h,mode);data.routes=[];if(mode==='food'){const center={x:w/2,y:h/2};data.nodes.forEach((p,i)=>data.routes.push(makeRoute(center,p,i%2?.04:.09)));data.explore=Array.from({length:9},()=>makeRoute(center,{x:rand(20,w-20),y:rand(20,h-20)},.22));}else if(mode==='tsp'){const tour=routeFrom(data.nodes);data.routes=[...tour.map((p,i)=>makeRoute(p,tour[(i+1)%tour.length],.035))];data.explore=data.nodes.slice(1).map(p=>makeRoute(data.nodes[0],p,.17));}else{const order=mode==='tokyo'?[0,1,2,4,5,7,6,3]:[0,1,2,3,4,5,6,7];const tour=order.map(i=>data.nodes[i]);data.routes=tour.slice(0,-1).map((p,i)=>makeRoute(p,tour[i+1],.025));data.explore=data.nodes.slice(1).map(p=>makeRoute(data.nodes[0],p,.14));}phase.textContent='Ready to explore';explain.textContent=copy[mode];out.textContent=count.value;count.style.display=mode==='food'?'':'none';document.querySelectorAll('.food-control').forEach(e=>e.style.display=mode==='food'?'':'none');draw();}
    function line(c,pts,progress,color,width,glow){const total=pts.length-1, at=clamp(progress,0,1)*total, upto=Math.floor(at);c.beginPath();c.moveTo(pts[0].x,pts[0].y);for(let i=1;i<=upto;i++)c.lineTo(pts[i].x,pts[i].y);if(upto<total){const q=at-upto,a=pts[upto],b=pts[upto+1];c.lineTo(a.x+(b.x-a.x)*q,a.y+(b.y-a.y)*q)}c.strokeStyle=color;c.lineWidth=width;c.shadowBlur=glow;c.shadowColor='#f3be38';c.stroke();c.shadowBlur=0;}
    function draw(){const [w,h,c]=fit(canvas);c.fillStyle='#07131b';c.fillRect(0,0,w,h);c.globalCompositeOperation='lighter';const p=clamp(tick/360,0,1);data.explore?.forEach((r,i)=>line(c,r,clamp(p*1.7-i*.08,0,1),`rgba(118,196,153,${p<.7?.24:.08})`,1.1,2));data.routes?.forEach((r,i)=>line(c,r,clamp(p*1.35-i*.045,0,1),mode==='food'&&i%3?'rgba(243,190,56,.7)':'rgba(243,190,56,.92)',mode==='food'&&i%3?2:3.5,mode==='food'&&i%3?7:15));data.nodes?.forEach((n,i)=>{c.shadowBlur=16;c.shadowColor='#f3be38';c.fillStyle='#f3be38';c.beginPath();c.arc(n.x,n.y,mode==='food'?7:5,0,TAU);c.fill();c.shadowBlur=0;if(n.label){c.fillStyle='rgba(238,244,247,.8)';c.font='11px DM Mono';c.fillText(n.label,n.x+8,n.y-8)}});if(mode==='food'){c.fillStyle='#fff4b2';c.beginPath();c.arc(w/2-2,h/2-2,4,0,TAU);c.fill()}c.globalCompositeOperation='source-over';}
    function step(){tick++;phase.textContent=tick<90?'Exploring many directions':tick<250?'Connecting food sources':'Reinforcing the strongest tubes';draw();if(running)raf=requestAnimationFrame(step)}
    start.onclick=()=>{running=!running;start.innerHTML=running?'Pause growth <span>Ⅱ</span>':'Resume growth <span>▶</span>';if(running)step()};reset.onclick=init;count.oninput=()=>{out.textContent=count.value;if(mode==='food')init()};document.querySelectorAll('.sim-tab').forEach(tab=>tab.onclick=()=>{mode=tab.dataset.sim;document.querySelectorAll('.sim-tab').forEach(t=>{t.classList.toggle('is-active',t===tab);t.setAttribute('aria-selected',t===tab?'true':'false')});init()});window.addEventListener('resize',init);init();
  }

  function metro(){const canvas=document.getElementById('metroCanvas'), start=document.getElementById('metroStart'), reset=document.getElementById('metroReset');let running=false,t=0,raf;const stations=[[.08,.8],[.18,.67],[.27,.56],[.37,.47],[.48,.37],[.6,.27],[.76,.21],[.9,.26],[.9,.47],[.88,.69],[.77,.82],[.61,.78],[.48,.68],[.34,.79],[.2,.86]];const paths=[[0,1,2,3,4,5,6,7],[0,1,2,3,4,8,9,10],[2,3,12,11,10],[3,13,14,0],[4,8,11,12,13]];
    function resetDraw(){t=0;running=false;cancelAnimationFrame(raf);draw()};function draw(){const [w,h,c]=fit(canvas);c.clearRect(0,0,w,h);c.globalCompositeOperation='lighter';const progress=clamp(t/500,0,1);paths.forEach((path,pi)=>{const upto=Math.floor(progress*(path.length-1));c.beginPath();for(let i=0;i<=upto;i++){const a=stations[path[i]],b=stations[path[Math.min(i+1,path.length-1)]];if(i===0)c.moveTo(a[0]*w,a[1]*h);else c.lineTo(a[0]*w,a[1]*h);if(i===upto&&progress*(path.length-1)>upto){const q=progress*(path.length-1)-upto;c.lineTo((a[0]+(b[0]-a[0])*q)*w,(a[1]+(b[1]-a[1])*q)*h)}}c.strokeStyle=pi<2?'rgba(243,190,56,.92)':'rgba(243,190,56,.3)';c.shadowBlur=pi<2?16:5;c.shadowColor='#f3be38';c.lineWidth=pi<2?4:2;c.stroke()});stations.forEach((s,i)=>{c.shadowBlur=12;c.shadowColor='#f3be38';c.fillStyle='#f3be38';c.beginPath();c.arc(s[0]*w,s[1]*h,i===0||i===10?8:4,0,TAU);c.fill();c.shadowBlur=0});c.globalCompositeOperation='source-over';if(running){t+=2;raf=requestAnimationFrame(draw)}}start.onclick=()=>{running=!running;start.innerHTML=running?'Pause growth <span>Ⅱ</span>':'Resume growth <span>▶</span>';if(running)draw()};reset.onclick=resetDraw;window.addEventListener('resize',draw);draw()}
  hero();growth();metro();
})();
